version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - ".:/var/www/html"
            - "laravel-storage:/var/www/html/storage"
            - "laravel-bootstrap-cache:/var/www/html/bootstrap/cache"
        ports:
            - "9000:9000"
        environment:
            DB_CONNECTION: "${DB_CONNECTION}"
            DB_HOST: db
            DB_PORT: "${DB_PORT}"
            DB_DATABASE: "${DB_DATABASE}"
            DB_USERNAME: "${DB_USERNAME}"
            DB_PASSWORD: "${DB_PASSWORD}"
            APP_KEY: "${APP_KEY}"
            APP_ENV: "${APP_ENV}"
            APP_DEBUG: "${APP_DEBUG}"
            APP_URL: "${APP_URL}"
        depends_on:
            - db
    nginx:
        image: "nginx:stable-alpine"
        container_name: laravel-nginx
        restart: unless-stopped
        volumes:
            - ".:/var/www/html"
            - "./nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8000:80"
        depends_on:
            - app
    db:
        image: "mysql:8.0"
        container_name: laravel-mysql
        restart: unless-stopped
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - "db-data:/var/lib/mysql"
        ports:
            - "3306:3306"
    memcached:
        image: "memcached:alpine"
        ports:
            - "${FORWARD_MEMCACHED_PORT:-11211}:11211"
        networks:
            - sail
    meilisearch:
        image: "getmeili/meilisearch:latest"
        ports:
            - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
        environment:
            MEILI_NO_ANALYTICS: "${MEILISEARCH_NO_ANALYTICS:-false}"
        volumes:
            - "sail-meilisearch:/meili_data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - "--no-verbose"
                - "--spider"
                - "http://127.0.0.1:7700/health"
            retries: 3
            timeout: 5s
volumes:
    db-data: {}
    laravel-storage: {}
    laravel-bootstrap-cache: {}
    sail-meilisearch:
        driver: local
